# Generated by Django 4.1 on 2022-09-13 08:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api_basics', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CreateGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('merchant_reference_id', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Ewallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ewallet', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Fields',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.TextField()),
                ('expiration_month', models.TextField()),
                ('expiration_year', models.TextField()),
                ('cvv', models.TextField()),
                ('name', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='MeataData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_defined', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.TextField()),
                ('currency', models.TextField()),
                ('ewallets', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api_basics.ewallet')),
            ],
        ),
        migrations.CreateModel(
            name='PaymentMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.TextField()),
                ('fields', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api_basics.fields')),
            ],
        ),
        migrations.CreateModel(
            name='TransactionData',
            fields=[
                ('transactionId', models.AutoField(default=None, primary_key=True, serialize=False)),
                ('source', models.TextField(default=None)),
                ('name', models.TextField(default=None)),
                ('destination', models.TextField()),
                ('amount', models.FloatField()),
                ('destinationName', models.TextField(default=None)),
            ],
        ),
        migrations.CreateModel(
            name='TransactionDataResponse',
            fields=[
                ('source', models.TextField(default=None, primary_key=True, serialize=False)),
                ('name', models.TextField(default=None)),
                ('destination', models.TextField()),
                ('amount', models.FloatField()),
            ],
        ),
        migrations.DeleteModel(
            name='Article',
        ),
        migrations.AddField(
            model_name='payment',
            name='payment_method',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api_basics.paymentmethod'),
        ),
        migrations.AddField(
            model_name='creategroup',
            name='metadata',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api_basics.meatadata'),
        ),
        migrations.AddField(
            model_name='creategroup',
            name='payments',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api_basics.payment'),
        ),
    ]
