# Generated by Django 4.0.7 on 2022-09-06 17:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_basics', '0002_customersdatanew'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomersDataNew',
        ),
    ]
