# Generated by Django 4.1 on 2022-09-10 10:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_basics', '0002_creategroup_ewallet_fields_meatadata_payment_and_more'),
        ('api_basics', '0003_delete_customersdatanew'),
    ]

    operations = [
    ]
