# Generated by Django 4.1 on 2022-09-11 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_basics', '0004_merge_20220910_1553'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactions',
            name='amount',
            field=models.IntegerField(),
        ),
    ]
