# Generated by Django 4.1 on 2022-09-11 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_basics', '0005_alter_transactions_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactions',
            name='amount',
            field=models.FloatField(),
        ),
    ]
